# Generated by Django 4.0.6 on 2022-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_car_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
